#!/bin/bash

#error cases
if [[ -e /usr/bin/pipe ]]; then
	echo "pipe: Could not install, a \"pipe\" command already exist on your system."
	exit 1
fi

if [[ -e /opt/Pipe_lang ]]; then
	echo "pipe: Could not install, A previous installation of Pipe_lang exists on your system."
	exit 1
fi

#nano coloration file installation (if nano installed)
mv nano/pipe.nanorc /usr/share/nano/pipe.nanorc 2> /dev/null && \
echo "Successfully installed Pipe syntax coloration file for nano editor."

#program installation
mkdir -p /opt
mv       $PWD               /opt/Pipe_lang && \
ln    -s /opt/Pipe_lang/run /usr/bin/pipe  && \
echo "Successfully installed Pipe_lang."
