#!/bin/bash



# ---- main ----
case $1 in

	#action 1 : help
	'' | '-h' | '--help')
		echo "Usage : pipe [action] [file]"
		echo "Executes a script written in language pipe."
		echo
		echo "Action :"
		echo "  -d, --debug  : Enable debug mode."
		echo "  -h, --help   : Show this help message."
		echo "  -u, --update : Update Pipe interpreter to the latest version."
		echo
		echo " Example :"
		echo "  > pipe myScript.pipe"
		echo "  #Executes program myScript.pipe without any debug."
		echo
		echo "More information about this language and interpreter at  :"
		echo "    https://github.com/iasebsil83/Pipe_lang"
		[[ $1 == '' ]] && exit 1
	;;

	#action 2 : update
	'-u' | '--update')

		#go in Pipe_lang directory
		oldPath=$(pwd)
		cd /opt/Pipe_lang

		#get the latest version from GitHub (https://github.com/iasebsil83/Pipe_lang)
		git pull && {
			#success
			echo "Pipe_lang updated !"
			cd $oldPath
		} || {
			#failure
			echo "pipe: Could not update Pipe_lang.";
			cd $oldPath
			exit 1
		}
	;;

	#action 3 : debug mode
	'-d' | '--debug')
		/./opt/Pipe_lang/src/main.py $@
	;;

	#undefined action
	-*)
		echo "pipe: Undefined action or argument '$1'."
		exit 1
	;;

	#action 4 : execute script
	*)
		/./opt/Pipe_lang/src/main.py $@
	;;
esac
